import enseeiht from 'assets/icons/enseeiht.png';
import aau from 'assets/icons/aau.jpg';
import kanop from 'assets/icons/kanop.png';
import lfdc from 'assets/icons/lfdc.png';
import akanthas from 'assets/icons/akanthas.jpg';

const details = {
  education: [
    {
      school: 'ENSEEIHT',
      url: 'https://www.enseeiht.fr/en/index.html',
      icon: enseeiht,
      location: 'Toulouse, France',
      degree: 'Master',
      major: 'Computer Science',
      start: 'Sep 2020',
      end: 'May 2023',
    },
    {
      school: 'AAU Klagenfurt',
      url: 'https://www.aau.at/en/',
      icon: aau,
      location: 'Klagenfurt, Austria',
      degree: 'Master',
      major: 'Computer Science',
      start: 'Sep 2022',
      end: 'Mar 2023',
    },
    {
      school: 'CPGE Lycée Déodat de Séverac',
      location: 'Toulouse, France',
      degree: 'Bachelor',
      major: 'Mathematics and Physics',
      start: 'Sep 2018',
      end: 'Jul 2020',
    },
    {
      school: 'Lycée Pierre de Fermat',
      location: 'Toulouse, France',
      degree: 'High School',
      major: 'Mathematics and Physics',
      start: 'Sep 2016',
      end: 'Jul 2018',
    },
  ],
  experience: [

    {
      company: 'Kanop',
      url: 'https://www.kanop.io/',
      icon: kanop,
      location: 'Paris, France',
      contract: 'Internship',
      position: 'Front-end web developer',
      start: 'Mar 2023',
      end: 'Sep 2023',
      description: 'Revamp of an outdated python flask codebase, documentation of project changes, following best practices for software development and web security, collaboration with UX designers, work with Deck.gl cartography and mass data rendering tools and adaptation to a constantly changing, deadline-driven environment.',
      technologies: ['React', 'Node JS', 'Gitlab CI/CD', 'Mapbox.gl', 'MUI Joy'],
    },
    {
      company: 'Kanop',
      url: 'https://www.kanop.io/',
      location: 'Klagenfurt, Austria (remote)',
      icon: kanop,
      contract: 'Freelance',
      position: 'Front-end web developer',
      start: 'Sep 2022',
      end: 'Feb 2023',
      description: 'Unit testing, optimization and redesign of web applications for scalability, speed, security and improved user experience.',
      technologies: ['REST API', 'Redux', 'SASS', 'WebGL', 'Typescript', 'Node JS', 'MUI Joy'],
    },
    {
      company: 'Kanop',
      url: 'https://www.kanop.io/',
      icon: kanop,
      location: 'Paris, France',
      contract: 'Internship',
      position: 'Front-end web developer',
      start: 'Jun 2022',
      end: 'Sep 2022',
      description: 'Revamp of an outdated python flask codebase, documentation of project changes, following best practices for software development and web security, collaboration with UX designers, work with Deck.gl cartography and mass data rendering tools and adaptation to a constantly changing, deadline-driven environment.',
      technologies: ['React', 'Node JS', 'Express', 'Gitlab CI/CD', 'Figma', 'WebGL', 'Mapbox.gl'],
    },
    {
      company: 'La Fresque du Climat',
      url: 'https://fresqueduclimat.org/',
      icon: lfdc,
      location: 'Toulouse, France',
      contract: 'Volunteering',
      position: 'Facilitator',
      start: 'Feb 2022',
      end: 'Jun 2022',
      description: 'Facilitation of workshops on climate change awareness',
    },
    {
      company: 'Akanthas',
      url: 'https://www.akanthas.fr/',
      icon: akanthas,
      location: 'Toulouse, France',
      contract: 'Internship',
      position: 'Data Processing & Management architecture developer',
      start: 'Jun 2021',
      end: 'Jul 2021',
      description: 'Development of continuous integration/deployment infrastructure, improvements to a Node JS web app and retrieval of image data from Arlo autonomous cameras via public API.',
      technologies: ['Node JS', 'Docker', 'GitHub CI/CD', 'Arlo API', 'React', 'Bootstrap', 'Microsoft Azure', 'Python', 'OpenCV'],
    },
  ],
  skills: {
    languages: [
      'JavaScript',
      'Typescript',
      'Python',
      'Java',
      'C',
      'C++',
      'Matlab',
      'HTML',
      'CSS',
      'SASS',
      'Julia',
      'OCaml',
    ],
    frameworks: [
      'React',
      'Node JS',
      'Express',
      'Git',
      'CI/CD',
      'Docker',
      'Linux',
      'Windows',
      'Keras',
    ],
    tools: [
      'Scrum',
      'Agile',
      'GitHub',
      'Gitlab',
      'Notion',
      'Figma',
      'Mapbox',
      'Deck.gl',
      'OpenCV',
      'MUI Joy',
      'Blender',
    ],
    others: [
      'REST API',
      'Multi-threading',
      'Multi-processing',
      'Object-oriented programming',
      'UML',
      'Design patterns',
      'MVC',
      'Functional programming',
      'Algorithms',
      '3D rendering',
      'OpenGL',
    ],
  },
};

export default details;
