name: Generate download assets
env:
  APP_ID: ${{ vars.BSODIUM_APP_ID }}
  APP_PRIVATE_KEY: ${{ secrets.BSODIUM_APP_PRIVATE_KEY }}

on:
  schedule:
    - cron: "0 0 * * 1" # Runs at 00:00 every Monday
  workflow_dispatch:

jobs:
  generate-resume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ env.APP_ID }}
          private-key: ${{ env.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Build resume download asset
        run: |
          yarn build-resume

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: rebuild resume download asset"
          commit_user_name: "BSoDium"
          commit_user_email: contact+github@bsodium.fr
